# Site settings
title: Anshul's Notes
email: anshulsinghchambial@gmail.com
description: "I dump my notes and thoughts here."
baseurl: ""
url: "http://anshulsc.github.io"
twitter_username: anshulsc
github_username:  anshulsc

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
